CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    migration_id character varying(150) NOT NULL,
    product_version character varying(32) NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220522220259_InitialMigration') THEN
    CREATE TABLE fabricante (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(80) NOT NULL,
        CONSTRAINT pk_fabricante PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220522220259_InitialMigration') THEN
    CREATE TABLE modelo (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(80) NOT NULL,
        fabricante_id integer NOT NULL,
        CONSTRAINT pk_modelo PRIMARY KEY (id),
        CONSTRAINT fk_modelo_fabricante_fabricante_id FOREIGN KEY (fabricante_id) REFERENCES fabricante (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220522220259_InitialMigration') THEN
    CREATE INDEX ix_modelo_fabricante_id ON modelo (fabricante_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220522220259_InitialMigration') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20220522220259_InitialMigration', '6.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220523163141_VeiculoEntity') THEN
    CREATE TABLE veiculo (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        modelo_id integer NOT NULL,
        renavam character(11) NOT NULL,
        ano integer NOT NULL,
        CONSTRAINT pk_veiculo PRIMARY KEY (id),
        CONSTRAINT fk_veiculo_modelo_modelo_id FOREIGN KEY (modelo_id) REFERENCES modelo (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220523163141_VeiculoEntity') THEN
    CREATE INDEX ix_veiculo_modelo_id ON veiculo (modelo_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220523163141_VeiculoEntity') THEN
    CREATE UNIQUE INDEX ix_veiculo_renavam ON veiculo (renavam);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220523163141_VeiculoEntity') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20220523163141_VeiculoEntity', '6.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220523225625_MotoristaEntity') THEN
    CREATE TABLE motorista (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nome character(60) NOT NULL,
        cpf character(11) NOT NULL,
        numero_cnh character(11) NOT NULL,
        veiculo_id integer NULL,
        CONSTRAINT pk_motorista PRIMARY KEY (id),
        CONSTRAINT fk_motorista_veiculo_veiculo_id FOREIGN KEY (veiculo_id) REFERENCES veiculo (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220523225625_MotoristaEntity') THEN
    CREATE UNIQUE INDEX ix_motorista_cpf ON motorista (cpf);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220523225625_MotoristaEntity') THEN
    CREATE UNIQUE INDEX ix_motorista_numero_cnh ON motorista (numero_cnh);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220523225625_MotoristaEntity') THEN
    CREATE UNIQUE INDEX ix_motorista_veiculo_id ON motorista (veiculo_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220523225625_MotoristaEntity') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20220523225625_MotoristaEntity', '6.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220529163127_ClienteEntity') THEN
    CREATE TABLE cliente (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(60) NOT NULL,
        cpf character(11) NOT NULL,
        data_cadastro timestamp without time zone NOT NULL,
        CONSTRAINT pk_cliente PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220529163127_ClienteEntity') THEN
    CREATE UNIQUE INDEX ix_cliente_cpf ON cliente (cpf);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220529163127_ClienteEntity') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20220529163127_ClienteEntity', '6.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220529174908_TelefoneClienteEntity') THEN
    CREATE TABLE telefone_cliente (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        cliente_id integer NOT NULL,
        numero character varying(15) NOT NULL,
        CONSTRAINT pk_telefone_cliente PRIMARY KEY (id),
        CONSTRAINT fk_telefone_cliente_cliente_cliente_id FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220529174908_TelefoneClienteEntity') THEN
    CREATE INDEX ix_telefone_cliente_cliente_id ON telefone_cliente (cliente_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220529174908_TelefoneClienteEntity') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20220529174908_TelefoneClienteEntity', '6.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220529184052_LocalizacaoEntity') THEN
    CREATE TABLE localizacao (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        cep character(11) NULL,
        uf character(2) NOT NULL,
        cidade character varying(40) NOT NULL,
        bairro character varying(40) NOT NULL,
        logradouro character varying(60) NOT NULL,
        numero character varying(12) NULL,
        complemento character varying(60) NULL,
        CONSTRAINT pk_localizacao PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220529184052_LocalizacaoEntity') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20220529184052_LocalizacaoEntity', '6.0.5');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220529191858_SolicitacaoEntity') THEN
    CREATE TABLE solicitacao (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        data_hora timestamp without time zone NOT NULL,
        cliente_id integer NOT NULL,
        motorista_id integer NOT NULL,
        localizacao_origem_id integer NOT NULL,
        localizacao_destino_id integer NOT NULL,
        CONSTRAINT pk_solicitacao PRIMARY KEY (id),
        CONSTRAINT fk_solicitacao_cliente_cliente_id FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE RESTRICT,
        CONSTRAINT fk_solicitacao_localizacao_localizacao_destino_id FOREIGN KEY (localizacao_destino_id) REFERENCES localizacao (id) ON DELETE RESTRICT,
        CONSTRAINT fk_solicitacao_localizacao_localizacao_origem_id FOREIGN KEY (localizacao_origem_id) REFERENCES localizacao (id) ON DELETE RESTRICT,
        CONSTRAINT fk_solicitacao_motorista_motorista_id FOREIGN KEY (motorista_id) REFERENCES motorista (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220529191858_SolicitacaoEntity') THEN
    CREATE INDEX ix_solicitacao_cliente_id ON solicitacao (cliente_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220529191858_SolicitacaoEntity') THEN
    CREATE INDEX ix_solicitacao_localizacao_destino_id ON solicitacao (localizacao_destino_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220529191858_SolicitacaoEntity') THEN
    CREATE INDEX ix_solicitacao_localizacao_origem_id ON solicitacao (localizacao_origem_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220529191858_SolicitacaoEntity') THEN
    CREATE INDEX ix_solicitacao_motorista_id ON solicitacao (motorista_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20220529191858_SolicitacaoEntity') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20220529191858_SolicitacaoEntity', '6.0.5');
    END IF;
END $EF$;
COMMIT;

